# netlify.toml

# Configuration de base pour la construction de votre projet Vite
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Configuration pour le développement local avec `netlify dev`
[dev]
  command = "npm run dev" # La commande pour démarrer votre serveur Vite
  targetPort = 8080       # Le port sur lequel Vite tourne (ne pas changer)
  port = 8888             # Le port sur lequel vous accéderez à votre site (ex: http://localhost:8888)
  publish = "dist"
  framework = "vite"

# Redirection pour que les appels à /api/chat fonctionnent
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200