# netlify.toml

# Configuration de base pour la construction du projet Vite
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Configuration pour le développement local avec `netlify dev`
[dev]
  command = "npm run dev" 
  targetPort = 8080       
  port = 8888             
  publish = "dist"
  framework = "vite"

# --- RÈGLES DE REDIRECTION ---

# Règle 1 : Spécifique pour les appels API (à venir)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Règle 2 : La règle "Attrape-Tout" pour la SPA ( MODIFICATION IMPORTANTE)
# Cette règle doit être la DERNIÈRE car elle est la plus générale.
# redirection vers index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200